name: Auto Assign Reviewers

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      members: read
    steps:
      - uses: actions/checkout@v4
      - uses: sebastiancoteanu/reviewer-assigner-action@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/reviewer-assignment.yml
